# frozen_string_literal: true

require "test_helper"
require "json"
require "taski/progress/info"
require "taski/progress/theme/default"
require "taski/progress/theme/detail"
require "taski/progress/theme/compact"
require "taski/progress/theme/plain"

# Byte-parity with the pre-replacement Liquid pipeline.
#
# test/fixtures/theme_parity_baseline.json was generated by rendering every
# shipped theme template through the OLD render_task_template /
# render_execution_template Liquid path (see the fixture's generated_from
# commit) across state/nil/boundary/spinner variants. Each case replays the
# same inputs against the Ruby-native theme methods and must produce the
# identical string — spinner glyphs, ANSI codes, truncation and all.
class TestThemeParity < Minitest::Test
  BASELINE = JSON.parse(
    File.read(File.expand_path("fixtures/theme_parity_baseline.json", __dir__))
  ).freeze

  THEMES = {
    "default" => Taski::Progress::Theme::Default,
    "detail" => Taski::Progress::Theme::Detail,
    "compact" => Taski::Progress::Theme::Compact,
    "plain" => Taski::Progress::Theme::Plain
  }.freeze

  def test_baseline_covers_all_themes_and_templates
    cases = BASELINE.fetch("cases")
    assert_equal 132, cases.size
    assert_equal THEMES.keys.sort, cases.map { |c| c["theme"] }.uniq.sort
    expected_methods = %w[
      task_pending task_start task_success task_fail task_skip
      clean_start clean_success clean_fail
      group_start group_success group_fail
      execution_start execution_running execution_complete execution_fail
    ]
    assert_equal expected_methods.sort, cases.map { |c| c["method"] }.uniq.sort
  end

  THEMES.each do |theme_name, theme_class|
    define_method(:"test_#{theme_name}_theme_matches_liquid_baseline") do
      theme = theme_class.new
      BASELINE.fetch("cases").each do |c|
        next unless c["theme"] == theme_name
        actual = theme.public_send(c["method"], task: build_task(c["task"]), execution: build_execution(c))
        assert_equal c["expected"], actual, "case #{c["id"]} diverged from the Liquid pipeline output"
      end
    end
  end

  private

  def build_task(t)
    return nil if t.nil?
    Taski::Progress::TaskInfo.new(
      name: t["name"],
      state: t["state"]&.to_sym,
      duration: t["duration"],
      error_message: t["error_message"],
      group_name: t["group_name"],
      stdout: t["stdout"]
    )
  end

  def build_execution(c)
    e = c.fetch("execution")
    Taski::Progress::ExecutionInfo.new(
      state: e["state"]&.to_sym,
      pending_count: e["pending_count"],
      done_count: e["done_count"],
      completed_count: e["completed_count"],
      failed_count: e["failed_count"],
      skipped_count: e["skipped_count"],
      total_count: e["total_count"],
      total_duration: e["total_duration"],
      root_task_name: e["root_task_name"],
      task_names: e["task_names"],
      spinner_index: c["spinner_index"]
    )
  end
end
